version: '3'
services:
  mysql:
    image: 'mysql:8.0.40'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=gorm
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  consul:
    image: "hashicorp/consul:1.15.4"
    ports:
      - "8500:8500"
